#!/usr/local/bin/perl -w

# $Id: classify,v 1.1.2.1 2004/04/19 17:29:05 dgrant Exp $

use strict;
use lib $ENV{'SBLIBPERL'};

use Text::Classify;
use Data::All;


$|++;

sub main()
{
    my $kw = get_keywords();
    my $ni = get_texts();
    
    
    my $tc = new Text::Classify({
        field_keyword   => 'Keyword', 
        field_text      => ['name', 'title']
    });
    
    print "Using ", scalar(@$kw), " keywords", "\n";
    print "Using ", scalar(@$ni), " new installs", "\n";
    print "Requires ", (scalar(@$ni)*scalar(@$kw)), " match calls", "\n";
    
    $tc->add_keywords($kw);
    
    $tc->search($ni);
    
    print "Success: ", $tc->reveal_success(), "\n";
}



sub get_keywords
{
    my $dsn  = 'DBI:mysql:database=cats;host=YOURHOST;port=3306';
    my $q    = 'SELECT  Keyword, Description FROM keywords WHERE HeadGroup_Id="DOM"';
    return _da($dsn, $q);
}

sub get_texts
{
    my $dsn  = 'DBI:mysql:database=cats;host=YOURHOST;port=3306';
    my $q    = "SELECT name, title FROM new_installs";
    return _da($dsn, $q);
}

sub _da
{
    return collection({
        path        => [shift, 'user', '7i75', shift],
        ioconf      => ['db', 'r' ]
    });
}

main();





#   Log$


